### ISSUE TITLE
update-silent for unattended update

### ISSUE THREAD

**Issue by gazlockwood** [novateams/nova.core#190]
https://github.com/novateams/nova.core/blob/ae951243d99901b1ffb792a7ad654f912990f18b/nova/core/roles/tuoni/tasks/install.yml#L7

The tuoni update command has an interactive requirement, using 

`tuoni update-silent `

will fix this

**Comment by AllRWeak** [comment]
For this repo the fix https://github.com/novateams/nova.core/pull/189/commits/4294e825e6baf266d7f5ab57ce86e31fda0a93c1 will be merged at one point. If you are using Catapult then it's already available https://github.com/ClarifiedSecurity/nova.core so closing the issue.
